version: "2.1"

services:

###########
# PHP CLI #
###########
  php-cli-debian:
    image: playsportsgroup/php:${PHP_VERSION}-cli${BRANCH}
    build:
      context: .
      args:
        VERSION: ${PHP_VERSION}
        PHP_EXTENSIONS: "dom gd intl mbstring pdo_mysql xsl zip soap bcmath opcache pcntl sockets"
      dockerfile: cli/Dockerfile

  php-cli-debian-xdebug:
    extends:
      service: php-cli-debian
    image: playsportsgroup/php:${PHP_VERSION}-cli-xdebug${BRANCH}
    build:
      args:
        XDEBUG: 1

  php-cli-alpine:
    image: playsportsgroup/php:${PHP_VERSION}-cli-alpine${BRANCH}
    build:
      context: .
      args:
        VERSION: ${PHP_VERSION}
        PHP_EXTENSIONS: "dom gd intl mbstring pdo_mysql xsl zip soap bcmath opcache pcntl sockets"
      dockerfile: cli/Dockerfile.alpine

  php-cli-alpine-xdebug:
    extends:
      service: php-cli-alpine
    image: playsportsgroup/php:${PHP_VERSION}-cli-xdebug-alpine${BRANCH}
    build:
      args:
        XDEBUG: 1

###########
# PHP FPM #
###########
  php-fpm-debian:
    image: playsportsgroup/php:${PHP_VERSION}-fpm${BRANCH}
    build:
      context: .
      args:
        VERSION: ${PHP_VERSION}
        PHP_EXTENSIONS: "dom gd intl mbstring pdo_mysql xsl zip soap bcmath opcache pcntl sockets"
      dockerfile: fpm/Dockerfile
  php-fpm-debian-xdebug:
    extends:
      service: php-fpm-debian
    image: playsportsgroup/php:${PHP_VERSION}-fpm-xdebug${BRANCH}
    build:
      args:
        XDEBUG: 1

  php-fpm-alpine:
    image: playsportsgroup/php:${PHP_VERSION}-fpm-alpine${BRANCH}
    build:
      context: .
      args:
        VERSION: ${PHP_VERSION}
        PHP_EXTENSIONS: "dom gd intl mbstring pdo_mysql xsl zip soap bcmath opcache pcntl sockets"
      dockerfile: fpm/Dockerfile.alpine

  php-fpm-alpine-xdebug:
    extends:
      service: php-fpm-alpine
    image: playsportsgroup/php:${PHP_VERSION}-fpm-xdebug-alpine${BRANCH}
    build:
      args:
        XDEBUG: 1
