version: "3"

services:

##################################
# CLI Versions: latest, 7.1, 7.2 #
##################################
  php-71-cli:
    image: ashsmith/php:7.1-cli
    build:
      context: .
      args:
        VERSION: "7.1"
        PHP_EXTENSIONS: "dom gd intl mbstring pdo_mysql pdo_pgsql xsl zip soap bcmath pcntl mcrypt"
      dockerfile: cli/Dockerfile
  php-72-cli:
    image: ashsmith/php:7.2-cli
    build:
      context: .
      args:
        VERSION: "7.2"
        PHP_EXTENSIONS: "dom gd intl mbstring pdo_mysql pdo_pgsql xsl zip soap bcmath"
      dockerfile: cli/Dockerfile


##################################
# FPM Versions: latest, 7.1, 7.2 #
##################################
  php-71-fpm:
    image: ashsmith/php:7.1-fpm
    build:
      context: .
      args:
        VERSION: "7.1"
        PHP_EXTENSIONS: "dom gd intl mbstring pdo_mysql pdo_pgsql xsl zip soap bcmath pcntl mcrypt"
      dockerfile: fpm/Dockerfile
  php-72-fpm:
    image: ashsmith/php:7.2-fpm
    build:
      context: .
      args:
        VERSION: "7.2"
        PHP_EXTENSIONS: "dom gd intl mbstring pdo_mysql pdo_pgsql xsl zip soap bcmath"
      dockerfile: fpm/Dockerfile