version: "2.1"

services:

##################################
# CLI Versions: 7.2, 7.3 #
##################################

  php-72-cli:
    image: playsportsgroup/php:7.2-cli-alpine-root${BRANCH}
    build:
      context: .
      args:
        VERSION: "7.2"
        PHP_EXTENSIONS: "dom gd intl mbstring pdo_mysql xsl zip soap bcmath opcache"
        FLAVOUR: alpine
      dockerfile: cli/Dockerfile

  php-72-cli-xdebug:
    extends:
      service: php-72-cli
    image: playsportsgroup/php:7.2-cli-xdebug-alpine-root${BRANCH}
    build:
      args:
        XDEBUG: 1

  php-73-cli:
    image: ashsmith/php:7.3-cli-alpine-root${BRANCH}
    build:
      context: .
      args:
        VERSION: "7.3"
        PHP_EXTENSIONS: "dom gd intl mbstring pdo_mysql xsl zip soap bcmath opcache"
        FLAVOUR: alpine
      dockerfile: cli/Dockerfile

  php-73-cli-xdebug:
    extends:
      service: php-73-cli
    image: ashsmith/php:7.3-cli-xdebug-alpine-root${BRANCH}
    build:
      args:
        XDEBUG: 1

##################################
# FPM Versions: 7.2, 7.3 #
##################################

  php-72-fpm:
    image: playsportsgroup/php:7.2-fpm-alpine-root${BRANCH}
    build:
      context: .
      args:
        VERSION: "7.2"
        PHP_EXTENSIONS: "dom gd intl mbstring pdo_mysql xsl zip soap bcmath opcache"
        FLAVOUR: alpine
      dockerfile: fpm/Dockerfile

  php-72-fpm-xdebug:
    extends:
      service: php-72-fpm
    image: playsportsgroup/php:7.2-fpm-xdebug-alpine-root${BRANCH}
    build:
      args:
        XDEBUG: 1

  php-73-fpm:
    image: playsportsgroup/php:7.3-fpm-alpine-root${BRANCH}
    build:
      context: .
      args:
        VERSION: "7.3"
        PHP_EXTENSIONS: "dom gd intl mbstring pdo_mysql xsl zip soap bcmath opcache"
        FLAVOUR: alpine
      dockerfile: fpm/Dockerfile

  php-73-fpm-xdebug:
    extends:
      service: php-73-fpm
    image: playsportsgroup/php:7.3-fpm-xdebug-alpine-root${BRANCH}
    build:
      args:
        XDEBUG: 1
