version: 2.1

commands:
  build_and_push:
    description: "Build & Push docker-compose images"
    parameters:
      variant:
        type: string
    steps:
      - checkout:
          path: ~/psg-docker-php
      - run: |
          echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
          export BRANCH=''
          if [ "$CIRCLE_BRANCH" != "master" ]; then
            export BRANCH="-${CIRCLE_BRANCH}"
          fi;
          echo "BRANCH=${BRANCH}" > .env
          docker-compose build php-<< parameters.variant >> php-<< parameters.variant >>-xdebug
          docker-compose push php-<< parameters.variant >> php-<< parameters.variant >>-xdebug

jobs:
  build_72_fpm:
    machine: true
    working_directory: ~/psg-docker-php/
    steps:
      - build_and_push:
          variant: '72-fpm'
  build_72_cli:
    machine: true
    working_directory: ~/psg-docker-php/
    steps:
      - build_and_push:
          variant: '72-cli'

  build_73_fpm:
    machine: true
    working_directory: ~/psg-docker-php/
    steps:
      - build_and_push:
          variant: '73-fpm'
  build_73_cli:
    machine: true
    working_directory: ~/psg-docker-php/
    steps:
      - build_and_push:
          variant: '73-cli'

workflows:
  version: 2
  btd:
    jobs:
      - build_72_fpm
      - build_72_cli
      - build_73_fpm
      - build_73_cli
