version: 2.1

commands:
  build_and_push:
    description: "Build & Push docker-compose images"
    parameters:
      variant:
        type: string
    steps:
      - checkout:
          path: ~/ashsmith-docker-php
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          export VARIANT=<< parameters.variant >>
          docker-compose build php-$VARIANT-fpm php-$VARIANT-cli php-$VARIANT-fpm-xdebug php-$VARIANT-cli-xdebug
          docker-compose push php-$VARIANT-fpm php-$VARIANT-cli php-$VARIANT-fpm-xdebug php-$VARIANT-cli-xdebug

jobs:
  build_71:
    machine: true
    working_directory: ~/ashsmith-docker-php/
    steps:
      - build_and_push:
          variant: '71'
  build_72:
    machine: true
    working_directory: ~/ashsmith-docker-php/
    steps:
      - build_and_push:
          variant: '72'
  build_73:
    machine: true
    working_directory: ~/ashsmith-docker-php/
    steps:
      - build_and_push:
          variant: '73'

workflows:
  version: 2
  btd:
    jobs:
      - build_71
      - build_72
      - build_73
