version: 2.1

commands:
  build_and_push:
    description: "Build & Push docker-compose images"
    parameters:
      image:
        type: string
      php_version:
        type: string
      distro:
        type: string
    steps:
      - checkout:
          path: ~/psg-docker-php
      - run: |
          echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
          export BRANCH=''
          if [ "$CIRCLE_BRANCH" != "master" ]; then
            export BRANCH="-${CIRCLE_BRANCH}"
          fi;
          echo "BRANCH=${BRANCH}" >> .env
          echo "PHP_VERSION=<< parameters.php_version >>" >> .env
          export SERVICE=php-<< parameters.image >>-<< parameters.distro >>
          docker-compose build $SERVICE $SERVICE-xdebug
          docker-compose push $SERVICE $SERVICE-xdebug

jobs:
  build:
    machine: true
    working_directory: ~/psg-docker-php/
    parameters:
      image:
        type: string
      php_version:
        type: string
      distro:
        type: string
    steps:
      - build_and_push:
          image: << parameters.image >>
          php_version: << parameters.php_version >>
          distro: << parameters.distro >>

workflows:
  version: 2
  build:
    jobs:
      - build:
          matrix:
            parameters:
              image: ["cli", "fpm"]
              php_version: ["7.3"]
              distro: ["alpine", "debian"]
